observation_sources: laser_scan_sensor point_cloud_sensor

#http://wiki.ros.org/costmap_2d/hydro/obstacles
laser_scan_sensor:
  sensor_frame: laser
  data_type: LaserScan
  topic: /scan_filtered
  marking: true
  clearing: true
  observation_persistence: 5 #How long to keep each sensor reading in seconds. A value of 0.0 will only keep the most recent reading.
  expected_update_rate: 0.5 #How often to expect a reading from a sensor in seconds. A value of 0.0 will allow infinite time between readings. This parameter is used as a failsafe to keep the navigation stack from commanding the robot when a sensor has failed. It should be set to a value that is slightly more permissive than the actual rate of the sensor. For example, if we expect a scan from a laser every 0.05 seconds we might set this parameter to be 0.1 seconds to give a generous buffer and account for some amount of system latency.
  #max_obstacle_height: 2.0
  #min_obstacle_height: 0.0
  #obstacle_range: 2.5
  #raytrace_range: 3.0 #The maximum range in meters at which to raytrace out obstacles from the map using sensor data.
  inf_is_valid: true
point_cloud_sensor:
  sensor_frame: /base_stabilized
  data_type: PointCloud2
  topic: /pav_pointCloud
  marking: true
  clearing: false
  observation_persistence: 20 #How long to keep each sensor reading in seconds. A value of 0.0 will only keep the most recent reading.
  expected_update_rate: 1.0 #How often to expect a reading from a sensor in seconds. A value of 0.0 will allow infinite time between readings. This parameter is used as a failsafe to keep the navigation stack from commanding the robot when a sensor has failed. It should be set to a value that is slightly more permissive than the actual rate of the sensor. For example, if we expect a scan from a laser every 0.05 seconds we might set this parameter to be 0.1 seconds to give a generous buffer and account for some amount of system latency.
  #max_obstacle_height: 2.0
  #min_obstacle_height: 0.0
  #obstacle_range: 2.5
  #raytrace_range: 3.0 #The maximum range in meters at which to raytrace out obstacles from the map using sensor data.
