#http://wiki.ros.org/costmap_2d/hydro/obstacles
#Global Filtering Parameters
obstacle_range: 4
raytrace_range: 4.5
min_obstacle_height: 0.0
max_obstacle_height: 2.0

#footprint: [[-0.33, -0.28], [-0.33, 0.28], [0.33, 0.28], [0.33, -0.28]]
footprint: [[-0.33, -0.28], [-0.33, 0.28], [0.33, 0.28], [0.33, -0.28]]
footprint_padding: 0

#robot_radius: 0.4
inflation_radius: 1.0 # the radius to which the cost scaling function is applied

transform_tolerance:  0.5
map_type: costmap #voxel 3d map
cost_scaling_factor: 2 #this parameter set the scaling factor that applies over the inflation. This parameter can be adjusted  so the robot has a more aggresive or conservative behaviour near obstacle (Robot operating system Complete reference (Volume 1) page 145)
