origin_latitude: 48.1541839 #48.1531010533
origin_longitude: 17.0724554267 #17.0743728117
map: "/home/mrvk/catkin_ws/src/osm_planner/osm_example/fei_edit.osm"
osm_map_path: "/home/mrvk/catkin_ws/src/osm_planner/osm_example/fei_edit.osm"
