local_costmap:
  global_frame: /map
  robot_base_frame: /base_link

  update_frequency: 5.0 # The frequency in Hz for the map to be updated.
  publish_frequency: 5.0 # The frequency in Hz for the map to publish display information.
  transform_tolerance: 1
  
  static_map: false
  rolling_window: true
  
  width: 10
  height: 10
  resolution: 0.05
