TrajectoryPlannerROS:
#Robot Configuration Parameters
  max_vel_x: 0.3
  #min_vel_x
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: -0.4
  max_in_place_vel_theta: 0.4
  
  #acceleration limits
  acc_lim_theta: 1
  acc_lim_x: 0.35

  escape_vel: -0.1
  holonomic_robot: false

#Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05      # default 0.05
  xy_goal_tolerance: 0.2        #default 0.1
  latch_xy_goal_tolerance: true           #default false If goal tollerance is latched, if the robot ever reach the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so

#Forward Simulation Parameters
  sim_time: 2.0 
#Trajectory Scoring Parameters
  meter_scoring: true
#Oscillation Prevention Parameters
  #oscillation_reset_dist (double, default 0.05) 
#Global Plan Parameters
  #prune_plan (bool, default true) 
